version: '3.9'

services:
  localhost:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
    volumes:
      - db-pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

    
  django_gunicorn:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static:/static
    env_file:
      - .env      
    depends_on:
      - localhost

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  db-pg-data:
  static:
