# Generated by Django 5.1 on 2024-08-19 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_total', models.FloatField(help_text='Área total da fazenda em hectares')),
                ('area_agricultavel', models.FloatField(help_text='Área agricultável em hectares')),
                ('area_vegetacao', models.FloatField(help_text='Área de vegetação em hectares')),
                ('culturas_plantadas', models.CharField(choices=[('Soja', 'Soja'), ('Milho', 'Milho'), ('Algodão', 'Algodão'), ('Café', 'Café'), ('Cana de Açúcar', 'Cana de Açúcar')], help_text='Culturas plantadas', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve ter 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve ter 14 dígitos numéricos.', regex='^\\d{14}$')])),
            ],
        ),
    ]
