# Generated by Django 5.1 on 2024-08-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtorrural',
            name='fazendas',
            field=models.ManyToManyField(related_name='ProdutorRural', to='fazenda.fazenda'),
        ),
    ]
