# Generated by Django 5.1 on 2024-08-19 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0002_produtorrural_fazendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtorrural',
            name='fazendas',
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='fazendas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProdutorRural', to='fazenda.fazenda'),
        ),
    ]
