# Generated by Django 5.1 on 2024-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0003_remove_produtorrural_fazendas_produtorrural_fazendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cidade',
            field=models.CharField(default='alem paraiba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fazenda',
            name='estado',
            field=models.CharField(default='MG', help_text='Exemplo: SP', max_length=2),
            preserve_default=False,
        ),
    ]
